CREATE TABLE `tblstudents` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `control` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `nickname` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `school` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `address` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `contact` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `gender` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `birthday` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `supervisor` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `designation` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `slapd` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `apdtitle` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `facility` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `department` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `hours` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `interview` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `validity` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `started` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `end` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `filename` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `filetype` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `filelocation` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `guardian` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `econtact` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `created` datetime NOT NULL,
 `modified` datetime NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;